-- ─── Tamweel Credit Decision Audit Log ─────────────────────────────────────
-- Run this in your Supabase SQL Editor.
-- This implements the immutable audit trail required by Part B / finding C8.
--
-- ── RLS ANALYSIS (Hardening Item 1) ─────────────────────────────────────────
-- Q: Does ONLY the backend (using the service-role key) write to this table,
--    or is there any path where a client-authenticated role inserts directly?
--
-- A: SERVICE-ROLE ONLY. The Supabase client in hybrid_engine.py uses the
--    SUPABASE_KEY environment variable which is the service-role JWT. The
--    service-role key BYPASSES RLS entirely in Supabase — this is by design
--    in Supabase's architecture.
--
--    Consequence for the INSERT policy below:
--    The policy "WITH CHECK (true)" is NEVER evaluated for service-role
--    writes. It would only be evaluated for anon or authenticated-role writes.
--    Since no client-side path touches this table, the policy is moot as a
--    security gate — but we keep it to document intent and to block any future
--    client-side path that might be accidentally added.
--
--    APPLICATION-LEVEL OWNERSHIP ASSERTION (the real guard):
--    In hybrid_engine.py run_pipeline(), before any INSERT to this table,
--    the code asserts:
--      asserted_email = user_data["_authenticated_email"]  (from JWT)
--      applicant_email = user_data["email"]
--      if asserted_email != applicant_email: BLOCK and return
--    This means a spoofed audit record under someone else's identity is
--    structurally impossible from the backend code path, independent of RLS.
--
--    If you ever want to add a client-direct INSERT path (not recommended),
--    replace the policy below with:
--      WITH CHECK (auth.jwt() ->> 'email' = applicant_email)
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. Create the audit log table
CREATE TABLE IF NOT EXISTS credit_decision_audit_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ── Who & When ──────────────────────────────────────────────────────────
    applicant_email TEXT NOT NULL,
    applicant_name  TEXT,
    decided_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- ── Model Provenance ────────────────────────────────────────────────────
    model_version   TEXT NOT NULL DEFAULT 'xgboost-classifier-v1',
    -- Bump model_version whenever the XGBoost model, scaler, or feature set is retrained.

    -- ── Raw Inputs (structured) ─────────────────────────────────────────────
    input_features  JSONB NOT NULL,
    -- Stores the full UserFinancialData dict so the decision can be replayed.
    -- Note: _authenticated_email and other internal keys are stripped before storage.

    -- ── Scores (deterministic — never from LLM) ─────────────────────────────
    ml_score_raw    NUMERIC(6,2) NOT NULL,
    final_score     NUMERIC(6,2) NOT NULL,
    score_breakdown JSONB NOT NULL,
    -- e.g. {"income_stability": 32.0, "bill_history": 24.0, "financial_health": 24.0}

    -- ── Decision ────────────────────────────────────────────────────────────
    risk_level          TEXT NOT NULL,
    decision            TEXT NOT NULL,
    approved_amount_jod INT  NOT NULL,

    -- ── LLM Explanation (text only — no numeric influence) ──────────────────
    explanation_reason      TEXT,
    explanation_strengths   TEXT[],
    explanation_risks       TEXT[],
    explanation_model       TEXT DEFAULT 'claude-sonnet-4-6',

    -- ── Financial Metrics Snapshot ──────────────────────────────────────────
    financial_metrics_snapshot JSONB
    -- Stores the financial_metrics dict used at decision time (savings_rate etc.)
);

-- 2. Enable RLS ────────────────────────────────────────────────────────────────
ALTER TABLE credit_decision_audit_log ENABLE ROW LEVEL SECURITY;

-- INSERT policy: allows service-role writes (which bypass this policy anyway).
-- No client-side INSERT path exists. If one is added in future, tighten to:
--   WITH CHECK (auth.jwt() ->> 'email' = applicant_email)
-- The application-level ownership assertion in hybrid_engine.py is the primary guard.
CREATE POLICY "audit_log_insert_only"
ON credit_decision_audit_log
FOR INSERT
WITH CHECK (true);

-- No SELECT, UPDATE, or DELETE policies — only service-role (admin) can read.
-- To allow applicants to read their own audit history, add:
-- CREATE POLICY "applicant_read_own_audit"
-- ON credit_decision_audit_log FOR SELECT
-- USING (auth.jwt() ->> 'email' = applicant_email);

-- 3. Index for fast applicant history lookup ──────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_audit_log_email
    ON credit_decision_audit_log (applicant_email, decided_at DESC);

-- 4. Add model_version column to tamweel_results ──────────────────────────────
-- (also included in add_role_column.sql — safe to run multiple times)
ALTER TABLE tamweel_results
    ADD COLUMN IF NOT EXISTS model_version TEXT DEFAULT 'xgboost-classifier-v1';
